<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit97ee78f17d0b95bfb2824523bb7b5c39
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Sample\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Sample\\' => 
        array (
            0 => __DIR__ . '/../..' . '/class',
        ),
    );

    public static $classMap = array (
        'AltoRouter' => __DIR__ . '/..' . '/altorouter/altorouter/AltoRouter.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit97ee78f17d0b95bfb2824523bb7b5c39::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit97ee78f17d0b95bfb2824523bb7b5c39::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit97ee78f17d0b95bfb2824523bb7b5c39::$classMap;

        }, null, ClassLoader::class);
    }
}
