<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit87bd667a2a1e94588f0b86ac90186f3c
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Shabadabada\\' => 12,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Shabadabada\\' => 
        array (
            0 => __DIR__ . '/../..' . '/class',
        ),
    );

    public static $classMap = array (
        'AltoRouter' => __DIR__ . '/..' . '/altorouter/altorouter/AltoRouter.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit87bd667a2a1e94588f0b86ac90186f3c::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit87bd667a2a1e94588f0b86ac90186f3c::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit87bd667a2a1e94588f0b86ac90186f3c::$classMap;

        }, null, ClassLoader::class);
    }
}
