<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'eb7e98e63c68d07fafdbd92bdcaa497e' => $vendorDir . '/deployer/recipes/autoload.php',
);
